//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScanCode.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScanCode.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity count.
        /// </summary>
        public static string ActivityCount_Header {
            get {
                return ResourceManager.GetString("ActivityCount_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add more.
        /// </summary>
        public static string AddMore_Label {
            get {
                return ResourceManager.GetString("AddMore_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add project.
        /// </summary>
        public static string AddProject_Label {
            get {
                return ResourceManager.GetString("AddProject_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing projects ....
        /// </summary>
        public static string AnalyzingProject_Label {
            get {
                return ResourceManager.GetString("AnalyzingProject_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CannotInsertOrRemoveVBAModuleCheckTrustSettings.
        /// </summary>
        public static string CannotInsertOrRemoveVBAModuleCheckTrustSettings {
            get {
                return ResourceManager.GetString("CannotInsertOrRemoveVBAModuleCheckTrustSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to choose project file or drag it into this window.
        /// </summary>
        public static string ChooseProject_Desc {
            get {
                return ResourceManager.GetString("ChooseProject_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your project to analyze:.
        /// </summary>
        public static string ChooseProject_Title {
            get {
                return ResourceManager.GetString("ChooseProject_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColumnExist.
        /// </summary>
        public static string ColumnExist {
            get {
                return ResourceManager.GetString("ColumnExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColumnNotExist.
        /// </summary>
        public static string ColumnNotExist {
            get {
                return ResourceManager.GetString("ColumnNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complexity Rank.
        /// </summary>
        public static string ComplexityRank_Header {
            get {
                return ResourceManager.GetString("ComplexityRank_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition Count.
        /// </summary>
        public static string ConditionCount_Header {
            get {
                return ResourceManager.GetString("ConditionCount_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm_Label {
            get {
                return ResourceManager.GetString("Confirm_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est. Effort(MD).
        /// </summary>
        public static string EstEffort_Header {
            get {
                return ResourceManager.GetString("EstEffort_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column number must be positive..
        /// </summary>
        public static string Exception_ColumnNumberNotValid {
            get {
                return ResourceManager.GetString("Exception_ColumnNumberNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception_CouldNot_InsertImage.
        /// </summary>
        public static string Exception_CouldNot_InsertImage {
            get {
                return ResourceManager.GetString("Exception_CouldNot_InsertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception_Couldnot_SetBorder.
        /// </summary>
        public static string Exception_Couldnot_SetBorder {
            get {
                return ResourceManager.GetString("Exception_Couldnot_SetBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception_Couldnot_SetColor.
        /// </summary>
        public static string Exception_Couldnot_SetColor {
            get {
                return ResourceManager.GetString("Exception_Couldnot_SetColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception_FileNotFound_WithFormat.
        /// </summary>
        public static string Exception_FileNotFound_WithFormat {
            get {
                return ResourceManager.GetString("Exception_FileNotFound_WithFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception_NotImageFile.
        /// </summary>
        public static string Exception_NotImageFile {
            get {
                return ResourceManager.GetString("Exception_NotImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project file cannot be empty.
        /// </summary>
        public static string Exception_ProjectFileCannotBeNull {
            get {
                return ResourceManager.GetString("Exception_ProjectFileCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving directory not found.
        /// </summary>
        public static string Exception_SavingDirectoryNotFound {
            get {
                return ResourceManager.GetString("Exception_SavingDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving file cannot be empty.
        /// </summary>
        public static string Exception_SavingFileCannotBeNull {
            get {
                return ResourceManager.GetString("Exception_SavingFileCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving file&apos;s name not valid.
        /// </summary>
        public static string Exception_SavingFileNameNotValid {
            get {
                return ResourceManager.GetString("Exception_SavingFileNameNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template file not found.
        /// </summary>
        public static string Exception_TemplateFileNotFound {
            get {
                return ResourceManager.GetString("Exception_TemplateFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export_Title {
            get {
                return ResourceManager.GetString("Export_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting projects ....
        /// </summary>
        public static string ExportingProject_Label {
            get {
                return ResourceManager.GetString("ExportingProject_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started.
        /// </summary>
        public static string GetStarted_Label {
            get {
                return ResourceManager.GetString("GetStarted_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        public static string Index_Header {
            get {
                return ResourceManager.GetString("Index_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsertColumnTableException_InsertColumnFail.
        /// </summary>
        public static string InsertColumnTableException_InsertColumnFail {
            get {
                return ResourceManager.GetString("InsertColumnTableException_InsertColumnFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License file:.
        /// </summary>
        public static string LicenseFile_Label {
            get {
                return ResourceManager.GetString("LicenseFile_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your license is invalid. Please retry with another files..
        /// </summary>
        public static string LicenseInvalid_Label {
            get {
                return ResourceManager.GetString("LicenseInvalid_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your license is valid..
        /// </summary>
        public static string LicenseValid_Label {
            get {
                return ResourceManager.GetString("LicenseValid_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location_Header {
            get {
                return ResourceManager.GetString("Location_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LockedRangeException.
        /// </summary>
        public static string LockedRangeException {
            get {
                return ResourceManager.GetString("LockedRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string MessageBox_CancelLabel {
            get {
                return ResourceManager.GetString("MessageBox_CancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string MessageBox_NoLabel {
            get {
                return ResourceManager.GetString("MessageBox_NoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string MessageBox_YesLabel {
            get {
                return ResourceManager.GetString("MessageBox_YesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Scan.
        /// </summary>
        public static string NewScan_Title {
            get {
                return ResourceManager.GetString("NewScan_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe next time.
        /// </summary>
        public static string NextTime_Label {
            get {
                return ResourceManager.GetString("NextTime_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoExcelFileIsCurrentlyOpened.
        /// </summary>
        public static string NoExcelFileIsCurrentlyOpened {
            get {
                return ResourceManager.GetString("NoExcelFileIsCurrentlyOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Points(MM).
        /// </summary>
        public static string ProcessPoint_Header {
            get {
                return ResourceManager.GetString("ProcessPoint_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be project.json file.
        /// </summary>
        public static string ProjectFile_Alert {
            get {
                return ResourceManager.GetString("ProjectFile_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Level.
        /// </summary>
        public static string ProjectLevel_Header {
            get {
                return ResourceManager.GetString("ProjectLevel_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name.
        /// </summary>
        public static string ProjectName_Header {
            get {
                return ResourceManager.GetString("ProjectName_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadCellException.
        /// </summary>
        public static string ReadCellException {
            get {
                return ResourceManager.GetString("ReadCellException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadOnlyCannotSaveException.
        /// </summary>
        public static string ReadOnlyCannotSaveException {
            get {
                return ResourceManager.GetString("ReadOnlyCannotSaveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadRangeException.
        /// </summary>
        public static string ReadRangeException {
            get {
                return ResourceManager.GetString("ReadRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready-to-scan Projects.
        /// </summary>
        public static string ReadyToScanTitle {
            get {
                return ResourceManager.GetString("ReadyToScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Summary.
        /// </summary>
        public static string ResultSummary_Title {
            get {
                return ResourceManager.GetString("ResultSummary_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveWorkbookException.
        /// </summary>
        public static string SaveWorkbookException {
            get {
                return ResourceManager.GetString("SaveWorkbookException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned Time: .
        /// </summary>
        public static string ScannedTime_Label {
            get {
                return ResourceManager.GetString("ScannedTime_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one project to start scanning..
        /// </summary>
        public static string SelectProject_Description {
            get {
                return ResourceManager.GetString("SelectProject_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select project from your computer.
        /// </summary>
        public static string SelectProject_Label {
            get {
                return ResourceManager.GetString("SelectProject_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select workspace.
        /// </summary>
        public static string SelectWorkspace_Description {
            get {
                return ResourceManager.GetString("SelectWorkspace_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SheetDoesNotExist.
        /// </summary>
        public static string SheetDoesNotExist {
            get {
                return ResourceManager.GetString("SheetDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet does not exist.
        /// </summary>
        public static string SheetNotExist {
            get {
                return ResourceManager.GetString("SheetNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SheetsRetrievalException.
        /// </summary>
        public static string SheetsRetrievalException {
            get {
                return ResourceManager.GetString("SheetsRetrievalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There might be some errors. Please try again..
        /// </summary>
        public static string SomeErrors_Title {
            get {
                return ResourceManager.GetString("SomeErrors_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start scanning.
        /// </summary>
        public static string StartScan_Label {
            get {
                return ResourceManager.GetString("StartScan_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total activities in all projects.
        /// </summary>
        public static string TotalActivities_Description {
            get {
                return ResourceManager.GetString("TotalActivities_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total activities.
        /// </summary>
        public static string TotalActivities_Title {
            get {
                return ResourceManager.GetString("TotalActivities_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total effort to convert by man day.
        /// </summary>
        public static string TotalEffort_Description {
            get {
                return ResourceManager.GetString("TotalEffort_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total effort.
        /// </summary>
        public static string TotalEffort_Title {
            get {
                return ResourceManager.GetString("TotalEffort_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total workflows in all projects.
        /// </summary>
        public static string TotalWorkflows_Description {
            get {
                return ResourceManager.GetString("TotalWorkflows_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total workflows.
        /// </summary>
        public static string TotalWorkflows_Title {
            get {
                return ResourceManager.GetString("TotalWorkflows_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again.
        /// </summary>
        public static string TryAgain_Label {
            get {
                return ResourceManager.GetString("TryAgain_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload your license file to start.
        /// </summary>
        public static string UploadLicense_Desc {
            get {
                return ResourceManager.GetString("UploadLicense_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Analyzer.
        /// </summary>
        public static string Welcome_Title {
            get {
                return ResourceManager.GetString("Welcome_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzer.
        /// </summary>
        public static string Window_Title {
            get {
                return ResourceManager.GetString("Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workbook does not exist.
        /// </summary>
        public static string WorkbookNotExist {
            get {
                return ResourceManager.GetString("WorkbookNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkbookNotSetOrClosed.
        /// </summary>
        public static string WorkbookNotSetOrClosed {
            get {
                return ResourceManager.GetString("WorkbookNotSetOrClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Count.
        /// </summary>
        public static string WorkflowCount_Header {
            get {
                return ResourceManager.GetString("WorkflowCount_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WriteCellException.
        /// </summary>
        public static string WriteCellException {
            get {
                return ResourceManager.GetString("WriteCellException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WriteDataTableAtRangeException.
        /// </summary>
        public static string WriteDataTableAtRangeException {
            get {
                return ResourceManager.GetString("WriteDataTableAtRangeException", resourceCulture);
            }
        }
    }
}
